# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: blue

# SEO
marketing:
  seo:
    site_type: Project
    local_business_type: ''
    org_name: ''
    description: 'A highly-customizable Hugo documentation theme powered by Hugo Blox website builder.'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    google_tag_manager: ''
    microsoft_clarity: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: ""
      # Logo filename in `assets/media/` folder
      filename: "logo.svg"
    show_search: true
    show_theme_chooser: true
    highlight_active_link: true
    show_translations: true
    hide_language_name: false

# Site footer
footer:
  copyright:
    notice: '© {year} Garage Education. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false
  show_translations: true

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features
features:
  math:
    enable: true
  privacy_pack:
    enable: true
  repository:
    url: 'https://github.com/garage-education/website'
    content_dir: 'content'
    branch: 'main'
  feedback:
    responses:
      positive: 'Glad to hear it! [Any ideas for improvements?](https://github.com/garage-education/website/issues/new).'
      negative: 'Sorry to hear that. [Please tell us how we can improve](https://github.com/garage-education/website/issues/new).'
  comment:
    provider: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
